### PR TITLE
mcc: add ignition version for ssh & registries machineconfigs

### LINKED ISSUE #498: MCC: ssh & registries MachineConfigs missing ignition versions
**Description**
Now that we are adding validation/upgrading Ignition, we need to make sure all generated machineconfigs have versions so that they are valid as per ignition logic. Currently this doesn't cause any issues, but let's be consistent.

**Steps to reproduce the issue:**
1. run installer
2. `oc get machineconfigs`
3. note that ssh & registries configs are missing ignition versions:
```
00-worker                                                   3.11.0-727-g17c4ed04-dirty   2.2.0             47m
00-worker-ssh                                               3.11.0-727-g17c4ed04-dirty                     47m
01-master-container-runtime                                 3.11.0-727-g17c4ed04-dirty   2.2.0             47m
01-master-kubelet                                           3.11.0-727-g17c4ed04-dirty   2.2.0             47m
01-worker-container-runtime                                 3.11.0-727-g17c4ed04-dirty   2.2.0             47m
01-worker-kubelet                                           3.11.0-727-g17c4ed04-dirty   2.2.0             47m
99-master-41133425-396b-11e9-bf36-06a669d3a32c-registries   3.11.0-727-g17c4ed04-dirty                     45m
99-worker-41153d9a-396b-11e9-bf36-06a669d3a32c-registries   3.11.0-727-g17c4ed04-dirty                     45m
```

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
**- What I did**

- [x] add ignition version for ssh machineconfig

- [x] add ignition version for 99-xxx-xxxx-registries

Closes: #498 
Pre-req for: #502 

**- How to verify it**
`oc get machineconfigs` should have a version for both.
also `e2e-aws` and `e2e-aws-op` in `artifacts/e2e-aws/machineconfigs.json` should show the ssh configs & registry configs as having version numbers.

### CODE REVIEW

File: pkg/controller/template/render.go [hunk 1]
```diff
@@ -99,6 +99,7 @@ func GenerateMachineConfigsForRole(config *RenderConfig, role string, path strin
 	var tempIgnConfig ignv2_2types.Config
 	tempUser := ignv2_2types.PasswdUser{Name: "core", SSHAuthorizedKeys: []ignv2_2types.SSHAuthorizedKey{ignv2_2types.SSHAuthorizedKey(config.SSHKey)}}
 	tempIgnConfig.Passwd.Users = append(tempIgnConfig.Passwd.Users, tempUser)
+	tempIgnConfig.Ignition.Version = "2.2.0"
```
Comment (runcom) [inline pkg/controller/template/render.go]: I know this is WIP but I've looked at the issue some days ago as well and we definitely need a single place where we build the machine-config skeleton with the version we want and when doing ssh/kubelet/containerruntime stuff we generate the skeleton with the version once and set every other piece we need on a case by case (if it doesn't make sense I can further explain)

Comment (kikisdeliveryservice) [reply pkg/controller/template/render.go]: yeah the ssh key would be straightforward for that, but still investigating how the kubelet/containerruntime is made since we didnt really write those. going to try to just get this fundamentally working first in the draft then optimise (if it makes sense).

**Comment by kikisdeliveryservice** [comment]
`1 cmd.go:330] Failed to obtain installer pod self-reference: Get https://172.30.0.1:443/api/v1/namespaces/openshift-kube-apiserver/pods/installer-7-ip-10-0-138-171.ec2.internal: dial tcp 172.30.0.1:443: connect: connection refused (will retry)\nNodeInstallerFailing: F0227 00:02:12.676858       1 cmd.go:84] Get https://172.30.0.1:443/api/v1/namespaces/openshift-kube-apiserver/pods/installer-7-ip-10-0-138-171.ec2.internal: dial tcp 172.30.0.1:443: connect: connection refused\nNodeInstallerFailing: `

/test e2e-aws-op

**Comment by kikisdeliveryservice** [comment]
`Feb 28 00:18:27 ip-10-0-9-44 bootkube.sh[4496]: Starting etcd certificate signer...
Feb 28 00:18:29 ip-10-0-9-44 bootkube.sh[4496]: bb5c0ffbcf13ef6b3a2642e2d3f92e73f88b526f916e0477a1042d24a41a518f
Feb 28 00:18:29 ip-10-0-9-44 bootkube.sh[4496]: Waiting for etcd cluster...`

/test e2e-aws-op

**Comment by kikisdeliveryservice** [comment]
aws timeouts/ rate limit
/retest

File: pkg/controller/template/render.go (hunk 1 above)
Comment (kikisdeliveryservice) [reply pkg/controller/template/render.go]: i have some ideas for a refactor that i'd like to discuss, but since this is needed for another PR (and works as is and contains an ssh refactor that aligns it with how the files/unit igns are done) I'd like to get this approved, get the mcc ignition check in to close 502 then come back to it.  wdyt @runcom  ?

Comment (kikisdeliveryservice) [reply pkg/controller/template/render.go]: also ci is finally green and i dont know when that will happen again.

File: pkg/controller/container-runtime-config/helpers.go [hunk 2]
```diff
@@ -123,6 +123,7 @@ func createNewRegistriesConfigIgnition(registriesTOMLConfig []byte) ignv2_2types
 		}
 		tempIgnConfig.Storage.Files = append(tempIgnConfig.Storage.Files, regTempFile)
 	}
+	tempIgnConfig.Ignition.Version = "2.2.0"
```
Comment (runcom) [inline pkg/controller/container-runtime-config/helpers.go]: Is there any way to avoid hardconding the version here? Floating strings are really bad generally (not your fault, just want to avoid them as much as possible)

Comment (cgwalters) [reply pkg/controller/container-runtime-config/helpers.go]: I think we probably want a common `NewIgnitionConfig()` helper somewhere, i.e.:
`tempIgnConfig := ignitionhelper.NewIgnitionConfig()`
and have that set the version.

**Comment by kikisdeliveryservice** [comment]
PR can be verified by checking the test logs in artifacts/e2e-aws-op/machineconfigs.json: 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/505/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/942/artifacts/e2e-aws-op/machineconfigs.json

and artifacts/e2e-aws/machineconfigs.json (when available)

File: pkg/controller/common/helpers.go [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+import (
+	ignv2_2types "github.com/coreos/ignition/config/v2_2/types"
+)
+
+// NewIgnConfig returns an empty ignition config with version set as 2.2.0
+func NewIgnConfig() ignv2_2types.Config {
+	var tempIgnConfig ignv2_2types.Config
+	tempIgnConfig.Ignition.Version = "2.2.0"
+	return tempIgnConfig
```
Comment (runcom) [inline pkg/controller/common/helpers.go]:
```
return ignv2_2types.Config{
    Ignition: ignv2_2types.Ignition{
        Version: "2.2.0",
    },
}
```

Comment (kikisdeliveryservice) [reply pkg/controller/common/helpers.go]: done!
