### PR TITLE
pkg/daemon: detect ssh accesses before daemon started

### LINKED ISSUE #379: Early ssh access detection
I'm surely missing some context but I believe the issue still holds. Anyone can currently ssh into nodes before the MCD runs or the login monitor goroutines is started leaving a window open where we won't detect that.

~~I was thinking (wrongly cause I don't know the installer code probably), can we completely disable the sshd service between the installer ending needing it, and have the MCD itself then start it through the systemd dbus api? Just a random thought (and guess) but I believe we can keep brainstorming here.~~

### PR DESCRIPTION
**Pull request by runcom**
Reads the journal checking for logind message ID and annotates the node
with the ssh accessed label if it finds out there were previous
accesses.

Close #379 

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
so, unit tests fail because of the CGO dep I've added:
```
2019/02/05 11:32:21 Resolved source https://github.com/openshift/machine-config-operator to master@649451d6, merging: #381 ce09d423 @runcom
2019/02/05 11:32:21 Resolved openshift/release:golang-1.10 to sha256:7e7effdd1615f3a25b54e9823fca1b572ae14b0b7b2b67a842d711ca2b31c22b
2019/02/05 11:32:21 Resolved openshift/origin-v4.0:base to sha256:acc19bd0ccecd3972fb4c3502bee570bddbd27f63dcdc39f17eb9035e8a7efd5
2019/02/05 11:32:21 Using namespace ci-op-bm4gs4v0
2019/02/05 11:32:21 Running [input:root], src, unit
2019/02/05 11:32:21 Creating namespace ci-op-bm4gs4v0
2019/02/05 11:32:21 Creating rolebinding for user runcom in namespace ci-op-bm4gs4v0
2019/02/05 11:32:21 Setting a soft TTL of 1h0m0s for the namespace
2019/02/05 11:32:21 Setting a hard TTL of 12h0m0s for the namespace
2019/02/05 11:32:21 Setting up pipeline imagestream for the test
2019/02/05 11:32:21 Tagging openshift/release:golang-1.10 into pipeline:root
2019/02/05 11:32:21 Building src
2019/02/05 11:32:21 Build src already succeeded in 24s
2019/02/05 11:32:21 Executing test unit
go test -v ./cmd/... ./pkg/... ./lib/...
# github.com/openshift/machine-config-operator/vendor/github.com/coreos/go-systemd/sdjournal
vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:33: fatal error: systemd/sd-journal.h: No such file or directory
 // #include <systemd/sd-journal.h>
                                 ^
compilation terminated.
```
Does anybody know how to add dependencies in that _build_ container which runs our unit tests?

**Comment by jlebon** [comment]
I think right now it's failing because it's trying to link it for all the container builds but the dep was only added for the daemon Dockerfiles. @abhinavdahiya mentioned in https://github.com/openshift/machine-config-operator/pull/335#issuecomment-459377601 that we should only turn on `CGO_ENABLED` for the MCD. Doing that should fix it, I think?

(Also, can you do the vendoring part as a separate commit; can probably just cherry-pick https://github.com/openshift/machine-config-operator/pull/335/commits/1068940e1e9bc538e99b998861afc9dbb4270c19 :)).

**Comment by cgwalters** [comment]
I believe the build container is derived from https://github.com/openshift/release/blob/a30cd48207d5f7244ed492450e111c6fbde5b757/projects/origin-release/golang-1.10/Dockerfile

I'm not sure about precedent for either adding to it or making a new one (or a derived container).

File: pkg/daemon/daemon.go [hunk 1]
```diff
@@ -240,6 +245,54 @@ func NewClusterDrivenDaemon(
...
+		if r == 0 {
+			break
+		}
+		entry, err := journal.GetEntry()
+		if err != nil {
+			return err
+		}
+		// this is so fragile, but from testing, it's pretty accurate as a way
+		// to detect if there were sessions created before we took over with the daemon
+		if entry != nil && strings.Contains(entry.Fields["MESSAGE"], "New session") {
```
Comment (jlebon) [inline pkg/daemon/daemon.go]: We don't even need to check the `MESSAGE` here. The msg id already represents the event we're looking for.

**Comment by runcom** [comment]
> @abhinavdahiya mentioned in [#335 (comment)](https://github.com/openshift/machine-config-operator/pull/335#issuecomment-459377601) that we should only turn on `CGO_ENABLED` for the MCD. Doing that should fix it, I think?

@jlebon I did that but still fails cause we're probably using another Dockerfile and image in tests (???)

> (Also, can you do the vendoring part as a separate commit; can probably just cherry-pick [1068940](https://github.com/openshift/machine-config-operator/commit/1068940e1e9bc538e99b998861afc9dbb4270c19) :)).

@jlebon is `dep` able to pull in vendors w/o a specific `import` in the code? in case it's not, I'd just wait for either PR to land and rebase the other one I guess. Otherwise, I'll create a separate commit.

> I'm not sure about precedent for either adding to it or making a new one (or a derived container).

thanks, I'll check that out

**Comment by cgwalters** [comment]
While it may seem like a hack honestly I'd say we just fork off that `journalctl` command as a subprocess.

**Comment by runcom** [comment]
> While it may seem like a hack honestly I'd say we just fork off that `journalctl` command as a subprocess.

that's fine with me

File: pkg/daemon/daemon.go [hunk 2]
```diff
@@ -240,6 +245,54 @@ func NewClusterDrivenDaemon(
...
+func (dn *Daemon) detectEarlySSHAccesses() error {
+	journal, err := sdjournal.NewJournal()
+	if err != nil {
+		return err
+	}
+	defer journal.Close()
+	if err := journal.AddMatch(logindNewSessionMessageIDMatch); err != nil {
+		return err
+	}
+	if err := journal.SeekHead(); err != nil {
```
Comment (jlebon) [inline pkg/daemon/daemon.go]: Right, but then restarting the node or MCD will always reinstall the annotation, even if it was manually cleared in the past. How about only doing this if we're bootstrapping? (See `getStateAndConfigs()`). Then from that point on, the login monitor will catch subsequent accesses. (Though it still leaves a tiny window during the time the nodes are restarted on upgrades).

File: pkg/daemon/daemon.go (hunk 1 above)
Comment (jlebon) [reply pkg/daemon/daemon.go]: Also, there's no need for a for loop here, right? We can just `.Next()` and then `.GetEntry()` sequentially.

**Comment by jlebon** [comment]
> @jlebon is `dep` able to pull in vendors w/o a specific `import` in the code?

I've just been doing `git add vendor/` and committing that separately first. GitHub does a good job of not expanding the vendoring churn in the "Files changed" tab, but in the terminal it's a pain to wade through.

**Comment by yuqi-zhang** [comment]
Running this locally shows: 
```
# WHAT=machine-config-daemon ./hack/build-go.sh
Using version from git...
Building github.com/openshift/machine-config-operator/cmd/machine-config-daemon (v3.11.0-573-g10b54e42)
# github.com/openshift/machine-config-operator/vendor/github.com/coreos/go-systemd/sdjournal
vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:11: fatal error: systemd/sd-journal.h: No such file or directory
 // #include <systemd/sd-journal.h>
           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by runcom** [comment]
yes, we're waiting for https://github.com/openshift/release/pull/2783 or go raw journalctl

File: pkg/daemon/daemon.go (hunk 1 above)
Comment (runcom) [reply pkg/daemon/daemon.go]: for the second point, just 1 entry is already enough to mark the node ssh/accessed so yeah, no need for a loop for sequentially calling `GetEntry`

File: pkg/daemon/daemon.go (hunk 2 above)
Comment (runcom) [reply pkg/daemon/daemon.go]: Fixed this and added another check on node startup after reboot

Comment (runcom) [reply pkg/daemon/daemon.go]: alright, this still doesn't cover the case when someone clears the annotation and you reboot on upgrades right? this will be called _at every boot_, correct?

Comment (runcom) [reply pkg/daemon/daemon.go]: Fixed here https://github.com/openshift/machine-config-operator/pull/381/files#diff-06b532a2a5a5d3ad1d5341b3e00945efR555

**Comment by ashcrow** [comment]
https://github.com/openshift/release/pull/2783 merged

**Comment by cgwalters** [comment]
So rhel-images will fail until the upstream change makes it there.  Not sure how long that will take.

File: hack/build-go.sh [hunk 3]
```diff
@@ -31,4 +31,4 @@ fi
 mkdir -p ${BIN_PATH}
 
 echo "Building ${REPO}/cmd/${WHAT} (${VERSION_OVERRIDE})"
-CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go build ${GOFLAGS} -ldflags "${GLDFLAGS}" -o ${BIN_PATH}/${WHAT} ${REPO}/cmd/${WHAT}
+CGO_ENABLED=1 GOOS=${GOOS} GOARCH=${GOARCH} go build ${GOFLAGS} -ldflags "${GLDFLAGS}" -o ${BIN_PATH}/${WHAT} ${REPO}/cmd/${WHAT}
```
Comment (jlebon) [inline hack/build-go.sh]: I made this conditional on the MCD only in https://github.com/openshift/machine-config-operator/pull/335/commits/c02eb5de6bcdff49931807070bbdd2cec2508087#diff-9283775b0feecc10455ec28bd08983b0.

Comment (jlebon) [reply hack/build-go.sh]: Hmm, actually that might not work. It looks like other components will then fail to build. From https://github.com/openshift/machine-config-operator/pull/335:

```
--> RUN WHAT=machine-config-controller ./hack/build-go.sh
Using version from git...
Building github.com/openshift/machine-config-operator/cmd/machine-config-controller (v3.11.0-589-gf62a5cf6-dirty)
vendor/github.com/coreos/go-systemd/sdjournal/functions.go...machine-config-operator/vendor/github.com/coreos/pkg/dlopen
error: build error: running 'WHAT=machine-config-controller ./hack/build-go.sh' failed with exit code 1
```

I'm not familiar enough with the golang build system, but it seems like it's trying to bundle all the vendored packages for all the targets instead of only the ones that actually need them?

Comment (runcom) [reply hack/build-go.sh]: it's because the daemon package imports other packages (controller|server) and the build system bundle them together and that's why it's required for other components as well.

Comment (abhinavdahiya) [reply hack/build-go.sh]: You can use build tags to include / build files only when those tags are set...
https://golang.org/pkg/go/build/#hdr-Build_Constraints

Comment (runcom) [reply hack/build-go.sh]: yeah, but that's gonna require some refactor as well

Comment (runcom) [reply hack/build-go.sh]: my point is yeah, we're going to refactor for build tags but I guess for this PR we can ship with CGO_ENABLED=1 anyway, I'm creating a new issue to track this.

Comment (runcom) [reply hack/build-go.sh]: https://github.com/openshift/machine-config-operator/issues/396

**Comment by ashcrow** [comment]
```
could not wait for build: the build machine-config-controller failed after 2m16s with reason DockerBuildFailed: Docker build strategy has failed.
```

**Comment by runcom** [comment]
rebased and removed the vendoring since #335 pulled it already

This should be ready

File: pkg/daemon/daemon.go [hunk 4]
```diff
@@ -252,6 +253,47 @@ func NewClusterDrivenDaemon(
...
+		return err
+	}
+	r, err := journal.Next()
+	if err != nil {
+		return err
+	}
+	// if the journal cursor has something
+	if r == 1 {
```
Comment (jlebon) [inline pkg/daemon/daemon.go]: Minor: could avoid the indentation here by checking for 0 and returning early.

Comment (runcom) [reply pkg/daemon/daemon.go]: thanks, fixed
